### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by StephanThierry** [buildkite/docker-puppeteer#100]
Whenever I call puppeteer from inside a Docker image based on this buildfile - I get this error:
(node:9) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[1125/075021.625772:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

It's just a simple: 
`var browser = await puppeteer.launch({ headless: true });`

On the provided link it says: IMPORTANT NOTE: The Linux SUID sandbox is almost but not completely removed.

So I'm not sure it's a viable strategy to use that - do you know a solution?

**Comment by toolmantim** [comment]
Sorry, but it's a limitation with running it in Docker (which should be already sandboxed for most practical purposes). If you pass `--no-sandbox` to the args when launching, it should fix it:

```js
browser = await puppeteer.launch({
    args: [
      // Required for Docker version of Puppeteer
      '--no-sandbox',
      '--disable-setuid-sandbox',
      // This will write shared memory files into /tmp instead of /dev/shm,
      // because Docker’s default for /dev/shm is 64MB
      '--disable-dev-shm-usage'
    ]
  })
```
