### ISSUE TITLE
Raspberry PI - Running Container

### ISSUE THREAD

**Issue by Istani** [buildkite/docker-puppeteer#103]
Hello,

I am Trying to run your Docker Container (Or Anything other with Chrome) on my Raspberry PI

Its installing just fine:

```
Sending build context to Docker daemon  4.608kB
Step 1/2 : FROM buildkite/puppeteer
 ---> 23a2e145eb22
Step 2/2 : CMD cd /app && node app.js
 ---> Running in ede1a47f24c0
Removing intermediate container ede1a47f24c0
 ---> 86d4fc5b2f41
Successfully built 86d4fc5b2f41
Successfully tagged node_puppeteer:latest

```

But on start with:
`docker run -it --name my_name-v ~/projects/my_app/:/app node_puppeteer bash`
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

Do you have any Idea how i could get it running?

**Comment by toolmantim** [comment]
Sorry this has taken so long to reply. How did you go getting this running? I might close the issue, but if you're still having problems feel free to re-open and we can help you out.

**Comment by Istani** [comment]
i didnt

**Comment by jkossis** [comment]
I am having this issue as well, anyone have any advice?

**Comment by jkossis** [comment]
@toolmantim could we have this re-opened? Still having this issue, unfortunately. Unless @Istani found a solution to the problem.

**Comment by Istani** [comment]
Sorry i didnt look more into it...
So yeah still an open issue

**Comment by jkossis** [comment]
After doing some research, it looks like it is an architecture issue. I found this example: https://github.com/pi-hole/docker-pi-hole/issues/519

It's probably being built for X86_64, whereas the pi runs on ARM.

**Comment by FezVrasta** [comment]
Any chance to get an arm build to support Apple Silicon?
