### ISSUE TITLE
Sturdiness concerns

### ISSUE THREAD

**Issue by rexagod** [buildkite/docker-puppeteer#105]
I just wanted to know if this docker image "just works", because my experience with puppeteer has been, let's say, not exactly good. I understand dockerizing something so broke and laced with bugs could be a cumbersome task to say the least, and I can do nothing but appreciate you folks for attempting (and succeeding at) that!

Cheers.

**Comment by toolmantim** [comment]
They’re fair concerns. It’s been solid for us, and plenty of other people too… and haven’t received too many reports otherwise.

**Comment by rexagod** [comment]
Glad to hear that, godspeed.
