### ISSUE TITLE
Fails with 'jest-puppeteer' due to missing 'procps' package

### ISSUE THREAD

**Issue by joaocarmo** [buildkite/docker-puppeteer#128]
I found this while using this image in GitLab's CI environment, using [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer). The default `globalTeardown` relies on the `ps` utility which is not included by default.

It errors out:

```txt
PASS functional-tests/app.test.js
Test Suites: 2 passed, 2 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        18.289 s
Ran all test suites.
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 119 ]
}
```

Currently, I need to install the `procps` package after pulling the image (using [before_script](https://docs.gitlab.com/ee/ci/yaml/#before_script-and-after_script)):

```sh
apt-get update && apt-get install -y procps
```

I suggest adding this to the base image instead.

**Comment by asafpelegcodes** [comment]
@toolmantim I've opened up https://github.com/buildkite/docker-puppeteer/pull/134 to add it to the base image.  I'm not sure if you accept forked PR's but if it helps at all then I'm happy to contribute.

Really appreciate this Docker image.  Thank you!

**Comment by ShivamJoker** [comment]
This has not been merged yet. Why ?

**Comment by joaocarmo** [comment]
@ShivamJoker, probably an abandoned project.

**Comment by asafpelegcodes** [comment]
@joaocarmo it's not abandoned, it was updated a month ago.

Maybe @jayco can help with PR #134? He merged in the last commit.

**Comment by joaocarmo** [comment]
@asafpelegcodes, you are correct. Though, since 2020, it seems most updates have been automatic versions bumps.
