### ISSUE TITLE
Failed to launch chrome - error loading libXss.so.1

### ISSUE THREAD

**Issue by sennerholt** [buildkite/docker-puppeteer#147]
Hi,

I’m suddenly getting following error in my production pipeline (bitbucket):

`Failed to launch chrome!
    /opt/atlassian/pipelines/agent/build/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`
    
I found a related issue in another project with the same problem:
https://github.com/atom/atom/issues/13176

Any thoughts on what could be the issue with this image?

Thanks

**Comment by jayco** [comment]
Hey @isaacSennerholt this should be fixed in the latest release, through https://github.com/buildkite/docker-puppeteer/pull/137
