### ISSUE TITLE
New to docker - "Timed out after 30000 ms while trying to connect to Chrome"

### ISSUE THREAD

**Issue by tobeorla** [buildkite/docker-puppeteer#24]
**O.S**: Windows 10
**Version**: latest
**Code**:
```js
        const puppeteer = require('puppeteer');
        const browser = await puppeteer.launch({
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage'
            ]
        });
        const page = await browser.newPage();
```
**Command**: ` docker run --rm -v ~/app/:/app/ buildkite/puppeteer:latest node /app/index.js`
**Error**:

`
(node:1) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r579032
`

I don't know if i'm running it propely as i'm new to docker :(

**Comment by toolmantim** [comment]
Hi @tobeorla! Sorry you're having troubles with the timeout error, and thanks for the great error report.

I gave the latest version a quick test here, on a Mac using Docker for Mac, and didn't hit that problem:
https://gist.github.com/toolmantim/6d5be00f2164cf9ec1d0d8aa592bb063

I don't have the capacity to debug a Windows machine myself I'm sorry. Can you try running with `-e DEBUG="puppeteer:*"` and see what the debug log lines show.

**Comment by tobeorla** [comment]
I ended up switching to native puppeteer for windows so i don't need docker :)

**Comment by toolmantim** [comment]
No worries @tobeorla — sounds like a more reliable solution for now anyhow!
