### ISSUE TITLE
Cannot start chrome

### ISSUE THREAD

**Issue by billaram** [buildkite/docker-puppeteer#35]
I m getting following error

 Cannot start Chrome
	[1030/100728.942574:ERROR:nacl_helper_linux.cc(310)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

**Comment by gokatz** [comment]
I'm facing a similar issue. Any help?

**Comment by toolmantim** [comment]
Have you set the `no-sandbox` flag @gokatz, similar to the example?

**Comment by gokatz** [comment]
Yes, I have set the `no-sandbox` flag. 
However, the setup is working fine in travis CI and only failing in Gitlab CI.
