### ISSUE TITLE
Connection error. When start containers

### ISSUE THREAD

**Issue by alpody** [buildkite/docker-puppeteer#44]
[webmaster@localhost docker-puppeteer]$ docker-compose -f docker-compose.integration-tests.yml build --pull
app uses an image, skipping
Building tests
Step 1/3 : FROM buildkite/puppeteer:latest
Trying to pull repository docker.io/buildkite/puppeteer ...
sha256:e5b161ca16d91782549b58976cfe6ebebaaa76f76a2b1c92680f91ce0e7542a0: Pulling from docker.io/buildkite/puppeteer
Digest: sha256:e5b161ca16d91782549b58976cfe6ebebaaa76f76a2b1c92680f91ce0e7542a0
Status: Image is up to date for docker.io/buildkite/puppeteer:latest
 ---> d8855571c3f2
Step 2/3 : RUN npm i mocha
 ---> Using cache
 ---> 3fe3dd0e414b
Step 3/3 : ENV PATH "${PATH}:/node_modules/.bin"
 ---> Using cache
 ---> 208126a81ee6
Successfully built 208126a81ee6
[webmaster@localhost docker-puppeteer]$ docker-compose -f docker-compose.integration-tests.yml run tests
Creating docker-puppeteer_app_1 ... done

Started HeadlessChrome/72.0.3617.0
  App
    1) renders

  0 passing (331ms)
  1 failing

  1) App
       renders:
     Error: net::ERR_CONNECTION_REFUSED at http://app/
      at navigate (/node_modules/puppeteer/lib/FrameManager.js:107:37)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    -- ASYNC --
      at Frame.<anonymous> (/node_modules/puppeteer/lib/helper.js:144:27)
      at Page.goto (/node_modules/puppeteer/lib/Page.js:624:49)
      at Page.<anonymous> (/node_modules/puppeteer/lib/helper.js:145:23)
      at Context.it (/integration-tests/index.test.js:37:33)
_______________________________________________________________________________________________________________
But when I use curl http://app/ in tests container, I have web page content from app container

**Comment by andymeek** [comment]
It actually works for me but I thought the example looks cryptic and it's very hard to tell what's going on - and I still don't understand it to be honest.

Maybe just update the `index.test.js` test to something simpler in order to get your test to pass.

For example:

```
describe('App', () => {
  it('renders', async () => {
    const response = await page.goto('http://google.com')
    assert(response.ok())
  })
})
```

**Comment by toolmantim** [comment]
I added `wait-for-it.sh` and cleaned up the examples in #55 — I think that should resolve this, but let me know if you're still seeing problems @alpody!
