### ISSUE TITLE
Question: As Node 10 being the base image - Any observations on Performance?

### ISSUE THREAD

**Issue by vposham** [buildkite/docker-puppeteer#61]
Im little confused to choose between this docker image and https://hub.docker.com/r/alekzonder/puppeteer/dockerfile this image as my base image.

From my research, I came to know that node 10 had some under the hood V8 engine improvements for Chromium. 

From performance point of view, Did you observe any difference when node 8 slim was used as base and changed to node 10?

Thanks 👍

**Comment by toolmantim** [comment]
Hi. Thanks for checking it out.

I've no idea as to the performance difference between the two images sorry! If you do some testing, or finding some information, please leave it here in the comments. Thanks!
