### ISSUE TITLE
Docker Hub tags aren't up to date

### ISSUE THREAD

**Issue by robbecoessens** [buildkite/docker-puppeteer#66]
Latest version in github is v1.13.0 but on Docker hub it's v1.11.0 ?

Can it be that Docker Hub doesn't automatically builds images for newest tags.

![image](https://user-images.githubusercontent.com/981628/54619572-1b332600-4a65-11e9-9355-2ca157bbf200.png)

**Comment by toolmantim** [comment]
Oh, looks like the Docker Hub permissions changes broke some things. I'll get that fixed, but in the meantime I've built and pushed the missing versions up there. Thanks for the heads up, and sorry about that!

**Comment by robbecoessens** [comment]
Thanks for the quick fix :-)

**Comment by toolmantim** [comment]
You're welcome! This has been fixed properly now, so they shouldn't become out of date again :)
