### ISSUE TITLE
Upgrade to Node.js v12

### ISSUE THREAD

**Issue by umaar** [buildkite/docker-puppeteer#80]
Any thoughts on using Node.js v12 in your Dockerfile? It comes with a bunch of performance enhancements + new features

https://nodejs.org/en/about/releases/

**Comment by toolmantim** [comment]
It’s a good question! I chose the LTS version mostly for less maintenance headaches. Do you need it in this Docker image for any reason in particular?

**Comment by umaar** [comment]
We're using this docker image for some automated tests but no biggie!

**Comment by joadr** [comment]
node v12 is now LTS
