### ISSUE TITLE
Excess line in docker-compose

### ISSUE THREAD

**Issue by woto** [buildkite/docker-puppeteer#90]
Hi, it is safe to remove links directive

https://github.com/buildkite/docker-puppeteer/blob/0c86af3725d085889c104ea04ce8e506a33c1ed9/example/docker-compose.integration-tests.yml#L11

https://docs.docker.com/compose/compose-file/compose-file-v2/#links

ps. Thank you for your work!

**Comment by toolmantim** [comment]
Thanks! Fixed in 7401646
