### ISSUE TITLE
Does puppeteer has it's own chromium

### ISSUE THREAD

**Issue by AlaaHamoudah** [buildkite/docker-puppeteer#91]
Why you are installing chrome and having all these installation statements in docker file, while you can use chromium from puppeteer itself?

**Comment by Aankhen** [comment]
From the Dockerfile:

https://github.com/buildkite/docker-puppeteer/blob/fd619fab40cd52639bcccaf5f05a5f46079283ba/Dockerfile#L9-L10

You could have Puppeteer skip its download, but [anything other than the specific revision it wants is not guaranteed to work](https://github.com/GoogleChrome/puppeteer/issues/288#issuecomment-322822607):

> Just note that the Puppeteer API is not guaranteed to work if you use a diff version of chrome.

**Comment by toolmantim** [comment]
Unfortunately we need to install Chromium, because otherwise you miss out on all the dependencies that are required by the bundled node binary. I've added a note here to hopefully explain the issue:
https://github.com/buildkite/docker-puppeteer/blob/master/Dockerfile#L13-L18

**Comment by bi-kai** [comment]
Same question, it's not easy to install Chrome in Centos cause of dependencies, the global installation maybe doing this step.
