### ISSUE TITLE
Update to puppeteer v2.0.0

### ISSUE THREAD

**Issue by lipp** [buildkite/docker-puppeteer#96]
PR created by bot:
https://github.com/buildkite/docker-puppeteer/pull/94

**Comment by akrawchyk** [comment]
@toolmantim is this a priority? The docker image is one major version release behind puppeteer upstream and 5 minor releases behind.

**Comment by toolmantim** [comment]
Sorry those versions weren't being published properly. We've just published a new version, but no v2.0.0 I'm afraid — straight to v3.0.1, and fixed it up so the automated builds are working correctly again.

**Comment by akrawchyk** [comment]
nice, thanks @toolmantim!
